# Generated by Django 2.1.1 on 2018-09-17 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('idImageType', models.AutoField(primary_key=True, serialize=False)),
                ('imageType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PresentationProjectData',
            fields=[
                ('idpresentationProjectData', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('returnOfInversion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('expirationDate', models.DateField()),
                ('initialInvestmentRound', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taretCapital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('video', models.FileField(upload_to='videos/%m/%d')),
                ('idProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsite.Project')),
            ],
        ),
        migrations.CreateModel(
            name='PresentationProjectImage',
            fields=[
                ('idPresentationProjectImage', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/%m/%d')),
                ('idImageType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsite.ImageType')),
                ('idPresentationProjectData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsite.PresentationProjectData')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='confirmationCode',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='usertransactionlog',
            name='transactionStatus',
            field=models.BooleanField(default=False),
        ),
    ]
