# Generated by Django 2.1.1 on 2018-09-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsite', '0002_auto_20180912_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='lastModification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
