# Generated by Django 2.1.1 on 2018-09-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsite', '0003_auto_20180912_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='crationDate',
            field=models.DateField(auto_now=True),
        ),
    ]
