# Generated by Django 2.1.1 on 2018-09-13 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsite', '0004_auto_20180912_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='idPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsite.Person'),
            preserve_default=False,
        ),
    ]
