# Generated by Django 2.1.1 on 2018-09-13 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsite', '0005_auto_20180912_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='idPerson',
        ),
    ]
