# Generated by Django 2.1.1 on 2018-09-13 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsite', '0008_remove_user_idperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsite.Person')
        ),
    ]
