# Generated by Django 2.1.1 on 2018-09-13 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsite', '0010_statusrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycrequest',
            name='idStatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bsite.StatusRequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kycrequest',
            name='reference',
            field=models.CharField(default='default', max_length=1000),
            preserve_default=False,
        ),
    ]
