# Generated by Django 2.1 on 2018-09-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsite', '0011_auto_20180913_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birdDate',
        ),
        migrations.AddField(
            model_name='person',
            name='birthDate',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(default='Colombia', max_length=50),
            preserve_default=False,
        ),
    ]
